from turtle import*
bgcolor('misty rose')
showturtle()
up()
def polygon(n, size=90):
    if n>2:
        kut=360/n
        for n in range (0,n):
            left(kut)
            forward(size)
width(6)
pencolor('black')
goto(0,0)
down()
fillcolor('light pink')
begin_fill()
polygon(8, size=60)
end_fill()
up()
width(4)
pencolor('sea green')
goto(-70,-250)
down()
fillcolor('green yellow')
begin_fill()
polygon(14, size=50)
end_fill()
up()
width(8)
pencolor('medium slate blue')
goto(150,-110)
down()
fillcolor('lavender')
begin_fill()
polygon(5, size=70)
end_fill()
up()
width(7)
color('red')
up()
goto(-80,-25)
down()
hideturtle()
write('Малова Валерія',font=('Times New Roman', 16,"bold"))
up()
exitonclick()
