from turtle import*
showturtle()
up()
#малюємо оранжеве коло
width(6)
pencolor('red')
goto(0,-90)
down()
fillcolor('dark orange')
begin_fill()
circle(190)
end_fill()
up()
#малюємо блакитне коло
width(5)
pencolor('yellow')
goto(0,-90)
down()
fillcolor('dodger blue')
begin_fill()
circle(160)
end_fill()
up()
#малюємо рожеве коло
width(5)
pencolor('medium orchid')
goto(0,-90)
down()
fillcolor('light pink')
begin_fill()
circle(130)
end_fill()
up()
#малюємо салатове коло
width(5)
pencolor('gray')
goto(0,-90)
down()
fillcolor('chartreuse')
begin_fill()
circle(100)
end_fill()
up()
#малюємо жовте коло
width(5)
pencolor('blue')
goto(0,-90)
down()
fillcolor('gold')
begin_fill()
circle(80)
end_fill()
up()
#малюємо сіре коло
width(5)
pencolor('black')
goto(0,-90)
down()
fillcolor('thistle')
begin_fill()
circle(40)
end_fill()
up()
#пишемо прізвище
width(7)
color('plum')
up()
goto(-60,-120)
down()
hideturtle()
write('Малова Валерія',font=('Times New Roman', 14,"bold"))
up()

